from aiogram.dispatcher.filters.state import StatesGroup, State


class State_list(StatesGroup):
    Q0 = State()
    Q1 = State()
    Q2 = State()
    Q3 = State()
    Q4 = State()
    Q5 = State()
    Q6 = State()
    Q7 = State()
    Q8 = State()
    Q9 = State()
    Q10 = State()
    Q11 = State()
    Q12 = State()
    Q13 = State()
    Q14 = State()
    Q15 = State()
    Q16 = State()
    Q17 = State()
    Q18 = State()
    Q19 = State()
    Q20 = State()
